#!/bin/bash
#
# Copyright 2015, Aaron W. @ohdns.org
# All Rights Reserved.
# This software may be freely redistributed and/or modified under the
# terms of the GNU General Public License as published by the Free
# Software Foundation; either version 2, or (at your option) any
# later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; see the file COPYING. If not, write to the
# Free Software Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
#
# Author: Aaron W. <githubspam@ohdns.org>
#
# do little harm.
/usr/bin/renice 19 -p $$ > /dev/null 2>&1
#
#  This script assumes that:
#   You have ISOs in ~/build/centos7_simple_kickstart/isos
#   Your VM's will live in ~/build/centos7_simple_kickstart/vm/__instance_name__
#
#  We are avoiding Vagrant on purpose so that you may
#  create this same environment anywhere.
#
# We need the extensionpack to get PXE for installing the first host, the kickstart server itself.
#  You can avoid that requirement by manually hitting the tab key when the ISO boots,
#  backing over the word "quiet" and typing:
#   cmdline nicdelay=10 ip=192.168.120.10 netmask=255.255.255.0 ks=http://192.168.120.1:8888/c7_ks.cfg
# ^  ^  ^  ^  ^
#  I AM SKIPPING THIS PROCESS and folks will have to manually
#  type 1 line when the FIRST VM boots for the first time.
#
# Our local "boot-strap" server is our laptop and it will have a private IP of 192.168.120.1
#
# Our Kickstart environment will have a private network of 192.168.120.0/24  (254 IP's usable)
#
# Our Kickstart server will be 192.168.120.10
#
# Our VM's will be in the 192.168.120.100-192.168.120.220 range.
#  Use 192.168.120.11 through 192.168.120.99 for static assignments in your testing,
#  or reserve the IP addresses in the dhcpd config.  Examples provided.
#
# Repo: https://github.com/ohdns/centos7_simple_kickstart.git
#
umask 007
#
PATH=${PATH}:/Applications/VirtualBox.app/Contents/MacOS:/bin:/sbin:/usr/bin:/usr/sbin
VM0="c7_small_kickstart"
export PATH USER VM0




######################################### Create vboxnet local interface
# VBox is slow to instantiate the interfaces and will return a result code before it completes...
VBOX_EXISTING_INTERFACE=`VBoxManage list -l hostonlyifs | grep -B3 "192\.168\.120\.1" | grep vboxnet | awk {'print $NF'}`
VBOX_EXISTING_COUNT=`VBoxManage list -l hostonlyifs | grep -B3 "192\.168\.120\.1" | grep -c vboxnet`
VBOX_NET_IS_UP=`ifconfig -a | grep -c "192\.168\.120\.1"`
#
 if [ ${VBOX_EXISTING_COUNT} -lt 1 ] ; then
  printf "\n\nCreating HostOnlyIF\n"
  OURHOSTONLYIF=`VBoxManage hostonlyif create 2>/dev/null | grep ^Interface | awk -F "\'" {'print $2'}`
  printf "Setting ${OURHOSTONLYIF} to 192.168.120.1 netmask 255.255.255.0\n\n"
  VBoxManage hostonlyif ipconfig ${OURHOSTONLYIF} --ip 192.168.120.1 --netmask 255.255.255.0
  VBoxManage dhcpserver remove --netname HostInterfaceNetworking-${OURHOSTONLYIF} 2>/dev/null
  export OURHOSTONLYIF
  sleep 2

 elif [ ${VBOX_EXISTING_COUNT} -gt 0 ] && [ ${VBOX_NET_IS_UP} -lt 1 ] ; then
  VBoxManage hostonlyif ipconfig ${VBOX_EXISTING_INTERFACE} --ip 192.168.120.1 --netmask 255.255.255.0
  VBoxManage dhcpserver remove --netname HostInterfaceNetworking-${VBOX_EXISTING_INTERFACE} 2>/dev/null
  OURHOSTONLYIF=`printf "${VBOX_EXISTING_INTERFACE}"`
  export OURHOSTONLYIF
  sleep 2

 elif  [ ${VBOX_EXISTING_COUNT} -gt 0 ] && [ ${VBOX_NET_IS_UP} -gt 0 ] ; then
  printf "\n\nLooks like we have an existing vboxnet interface of ${VBOX_EXISTING_INTERFACE}.\n\n"
  OURHOSTONLYIF=`printf "${VBOX_EXISTING_INTERFACE}"`
  export OURHOSTONLYIF
  sleep 2

 else
  printf "\n\nUnable to determine a way to bring up our vboxnet internface.\n\n"
  exit 2
 fi
#
sync
######################################### Create vboxnet local interface







######################################### CENTOS EPEL Repo exist? Repo current? If not, create or update it.
printf "\n\nSyncing Public to Local Repo Copies.\n\nIMPORTANT: Avoid running this more than 4 times per day from your network to avoid being blocked.\n\n";sleep 4
mkdir -p ${HOME}/build/centos7_simple_kickstart/etc
mkdir -p ${HOME}/build/centos7_simple_kickstart/scripts
mkdir -p ${HOME}/build/centos7_simple_kickstart/tmp
mkdir -p ${HOME}/build/centos7_simple_kickstart/log
mkdir -p ${HOME}/build/centos7_simple_kickstart/www/html/mirror/centos/7/isos/x86_64
mkdir -p ${HOME}/build/centos7_simple_kickstart/www/html/mirror/centos/7/os/x86_64
mkdir -p ${HOME}/build/centos7_simple_kickstart/www/html/mirror/centos/7/updates/x86_64
mkdir -p ${HOME}/build/centos7_simple_kickstart/www/html/mirror/centos/7/extras/x86_64
mkdir -p ${HOME}/build/centos7_simple_kickstart/www/html/mirror/epel/7/x86_64
mkdir -p ${HOME}/build/centos7_simple_kickstart/www/html/mirror/docker_images
#
# rsync command and arguments.
RS="rsync -avH --progress --delay-updates --delete --delete-after --exclude=repoview/ --exclude=debug/ --exclude=drpms/";export RS
#
# CENTOS
${RS} mirrors.kernel.org::centos/7/isos/x86_64/CentOS*NetInstall*.iso ${HOME}/build/centos7_simple_kickstart/www/html/mirror/centos/7/isos/x86_64/.
${RS} mirrors.kernel.org::centos/7/os/x86_64/. ${HOME}/build/centos7_simple_kickstart/www/html/mirror/centos/7/os/x86_64/.
${RS} mirrors.kernel.org::centos/7/updates/x86_64/. ${HOME}/build/centos7_simple_kickstart/www/html/mirror/centos/7/updates/x86_64/.
${RS} mirrors.kernel.org::centos/7/extras/x86_64/. ${HOME}/build/centos7_simple_kickstart/www/html/mirror/centos/7/extras/x86_64/.
#
##  EPEL
##  Comment out the next line if you do NOT want a copy of the Fedora EPEL repo.  It is about 8GB.
${RS} mirrors.cat.pdx.edu::fedora-epel/7/x86_64/. ${HOME}/build/centos7_simple_kickstart/www/html/mirror/epel/7/x86_64/.

#
curl -A Mozilla -s https://wiki.centos.org/Manuals/ReleaseNotes/CentOS7 -o ${HOME}/build/centos7_simple_kickstart/www/html/mirror/c7_notes.html
shasum -a 256 ${HOME}/build/centos7_simple_kickstart/isos/x86_64/CentOS*netInstal*.iso > ${HOME}/build/centos7_simple_kickstart/isos/x86_64/.validate_iso.txt
NOTESUM=`egrep "CentOS.*NetInsta.*\.iso" ${HOME}/build/centos7_simple_kickstart/www/html/mirror/c7_notes.html | awk -F ">" {'print $3'} | awk {'print $1'}`
LOCALSUM=`awk {'print $1'} ${HOME}/build/centos7_simple_kickstart/isos/x86_64/.validate_iso.txt`
printf "\n\nChecksum of ISO from centos.org: ${NOTESUM}\nChecksum of Local ISO: ${LOCALSUM}\n\n"
#
#
# DO NOT GET THESE FILES FROM A MIRROR.  Sorry, centos.org doesn't provide https on this site, derp.
if [ ! -f ${HOME}/build/centos7_simple_kickstart/www/html/mirror/RPM-GPG-KEY-CentOS-7 ] ; then
curl -A Mozilla -s http://mirror.centos.org/centos/7/os/x86_64/RPM-GPG-KEY-CentOS-7 -o ${HOME}/build/centos7_simple_kickstart/www/html/mirror/RPM-GPG-KEY-CentOS-7
chmod 1444 ${HOME}/build/centos7_simple_kickstart/www/html/mirror/RPM-GPG-KEY-CentOS-7
fi
if [ ! -f ${HOME}/build/centos7_simple_kickstart/www/html/mirror/RPM-GPG-KEY-EPEL-7 ] ; then
curl -A Mozilla -s https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-7 -o ${HOME}/build/centos7_simple_kickstart/www/html/mirror/RPM-GPG-KEY-EPEL-7
chmod 1444 ${HOME}/build/centos7_simple_kickstart/www/html/mirror/RPM-GPG-KEY-EPEL-7
fi
######################################### CENTOS EPEL Repo exist? Repo current? If not, create or update it.


mkdir -p ${HOME}/build/centos7_simple_kickstart/www/html
mkdir -p ${HOME}/build/centos7_simple_kickstart/logs
mkdir -p ${HOME}/build/centos7_simple_kickstart/tmp
mkdir -p ${HOME}/build/centos7_simple_kickstart/etc
chmod 0755 ${HOME}/build/centos7_simple_kickstart/www/html
chmod 0700 ${HOME}/build/centos7_simple_kickstart/tmp
chmod 0700 ${HOME}/build/centos7_simple_kickstart/etc
cp ${HOME}/build/centos7_simple_kickstart/scripts/c7*cfg ${HOME}/build/centos7_simple_kickstart/www/html/
chmod 0644 ${HOME}/build/centos7_simple_kickstart/www/html/c7*cfg

exit 0;
